# -*- coding: utf-8 -*-
"""Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pn7Iv7dm38ixdUYatFl9mhPORx-BJJw7
"""

#Question 1
import re
a=open("onelinefile.txt",'r')

l=[]
l[:0]=a

for i in range(1,len(l)-1):
        s=str(a[i-1]+a[i]+a[i+1])
        #print(s)
        if re.match("[a-zA-Z][0-9][a-zA-Z]",s):
            l.insert(i,"\n")
print(",".join(l))

#Question 2
import pandas as pd
import numpy as np
import random




missing_value_formats = ["NA","NaN"]
df = pd.read_csv("Q2-Dataset.csv", na_values = missing_value_formats)
print(df.head())
def make_format(i):
    if i is int:
      return i 
    else:
      return random.randint(0,1000)

df['Alley'] = df['Alley'].map(make_format)
print(df.head())

#Question 3
a=[]
atleast=[]
num=0
with open("about.txt", "r") as rf:
  for line in rf:
    a.extend(line.split())

  for i in a:
    if(len(i)>=6):
      atleast.append(i)
  
  num=len(atleast)
print("the words with atleast 6 letters are:")
print(atleast)
print("total numbers of words :",num)